<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Permission definitions
    |--------------------------------------------------------------------------
    | slug => [name, group]
    */
    'permissions' => [
        // Dashboard
        'dashboard.view' => ['View dashboard', 'dashboard'],

        // Organization
        'organization.companies.view' => ['View companies', 'organization'],
        'organization.companies.manage' => ['Manage companies', 'organization'],
        'organization.branches.view' => ['View branches', 'organization'],
        'organization.branches.manage' => ['Manage branches', 'organization'],
        'organization.stores.view' => ['View stores', 'organization'],
        'organization.stores.manage' => ['Manage stores', 'organization'],
        'organization.warehouses.view' => ['View warehouses', 'organization'],
        'organization.warehouses.manage' => ['Manage warehouses', 'organization'],
        'organization.devices.view' => ['View devices', 'organization'],
        'organization.devices.manage' => ['Manage devices', 'organization'],
        'organization.currencies.view' => ['View currencies', 'organization'],
        'organization.currencies.manage' => ['Manage currencies', 'organization'],
        'organization.payment_methods.view' => ['View payment methods', 'organization'],
        'organization.payment_methods.manage' => ['Manage payment methods', 'organization'],

        // Catalog
        'catalog.catalogs.view' => ['View catalogs', 'catalog'],
        'catalog.catalogs.manage' => ['Manage catalogs', 'catalog'],
        'catalog.categories.view' => ['View categories', 'catalog'],
        'catalog.categories.manage' => ['Manage categories', 'catalog'],
        'catalog.products.view' => ['View products', 'catalog'],
        'catalog.products.manage' => ['Manage products', 'catalog'],
        'catalog.barcodes.view' => ['View barcodes', 'catalog'],
        'catalog.barcodes.manage' => ['Manage barcodes', 'catalog'],

        // Sales
        'sales.view' => ['View sales', 'sales'],
        'sales.create' => ['Create sales', 'sales'],
        'sales.void' => ['Void sales', 'sales'],
        'sales.refund' => ['Refund sales', 'sales'],
        'sales.return' => ['Process sale returns', 'sales'],
        'sales.discount.apply' => ['Apply discounts', 'sales'],
        'promotions.view' => ['View promotions', 'promotions'],
        'promotions.manage' => ['Manage promotions', 'promotions'],

        // Cash registers (Phase 20)
        'registers.view' => ['View cash registers', 'registers'],
        'registers.manage' => ['Manage cash registers', 'registers'],
        'registers.session.open' => ['Open register session', 'registers'],
        'registers.session.close' => ['Close register session', 'registers'],
        'registers.movement.record' => ['Record cash movements', 'registers'],

        // Cashier shifts (Phase 21)
        'shifts.view' => ['View cashier shifts', 'shifts'],
        'shifts.manage' => ['Manage cashier shifts', 'shifts'],
        'shifts.open' => ['Open cashier shift', 'shifts'],
        'shifts.close' => ['Close cashier shift', 'shifts'],
        'shifts.movement.record' => ['Record shift cash movements', 'shifts'],

        // Inventory
        'inventory.view' => ['View inventory', 'inventory'],
        'inventory.manage' => ['Manage inventory', 'inventory'],
        'inventory.adjust' => ['Adjust stock', 'inventory'],
        'inventory.transfer' => ['Transfer stock', 'inventory'],
        'inventory.count.create' => ['Create inventory count', 'inventory'],
        'inventory.count.enter' => ['Enter inventory count quantities', 'inventory'],
        'inventory.count.review' => ['Review inventory count', 'inventory'],
        'inventory.count.approve' => ['Approve inventory count and post adjustments', 'inventory'],
        'inventory.cycle.configure' => ['Configure cycle count rules', 'inventory'],

        // Expenses
        'expenses.view' => ['View expenses', 'expenses'],
        'expenses.manage' => ['Manage expenses', 'expenses'],
        'expenses.create' => ['Create expense', 'expenses'],
        'expenses.submit' => ['Submit expense', 'expenses'],
        'expenses.approve' => ['Approve expense', 'expenses'],
        'expenses.pay' => ['Pay expense', 'expenses'],
        'expenses.cancel' => ['Cancel expense', 'expenses'],
        'expenses.categories' => ['Manage expense categories', 'expenses'],
        'expenses.recurring' => ['Manage recurring expenses', 'expenses'],
        'expenses.reports' => ['View expense reports', 'expenses'],
        'expenses.export' => ['Export expense reports', 'expenses'],
        'expenses.budgets' => ['Manage expense budgets', 'expenses'],

        // Purchases
        'purchases.view' => ['View purchases', 'purchases'],
        'purchases.manage' => ['Manage purchases', 'purchases'],
        'purchases.receive' => ['Receive goods', 'purchases'],
        'purchases.requisition.create' => ['Create requisition', 'purchases'],
        'purchases.requisition.approve' => ['Approve requisition', 'purchases'],
        'purchases.proforma.create' => ['Create proforma', 'purchases'],
        'purchases.proforma.approve' => ['Approve proforma', 'purchases'],
        'purchases.order.create' => ['Create purchase order', 'purchases'],
        'purchases.order.approve' => ['Approve purchase order', 'purchases'],
        'purchases.invoice.create' => ['Create supplier invoice', 'purchases'],
        'purchases.invoice.approve' => ['Approve supplier invoice', 'purchases'],
        'purchases.payment.create' => ['Make supplier payment', 'purchases'],
        'purchases.payment.approve' => ['Approve supplier payment', 'purchases'],
        'purchases.return.create' => ['Create purchase return', 'purchases'],
        'purchases.return.approve' => ['Approve purchase return', 'purchases'],
        'purchases.export' => ['Export purchase reports', 'purchases'],
        'purchases.delete' => ['Delete purchase documents', 'purchases'],

        // Customers
        'customers.view' => ['View customers', 'customers'],
        'customers.manage' => ['Manage customers', 'customers'],

        // Suppliers
        'suppliers.view' => ['View suppliers', 'suppliers'],
        'suppliers.manage' => ['Manage suppliers', 'suppliers'],

        // Admin / RBAC
        'users.view' => ['View users', 'admin'],
        'users.manage' => ['Manage users', 'admin'],
        'roles.view' => ['View roles', 'admin'],
        'roles.manage' => ['Manage roles', 'admin'],

        // Reports & accounting
        'reports.view' => ['View reports', 'reports'],
        'reports.export' => ['Export reports', 'reports'],
        'accounting.view' => ['View accounting', 'accounting'],
        'accounting.manage' => ['Manage accounting', 'accounting'],

        // Audit
        'audit.view' => ['View audit logs', 'audit'],

        // Settings
        'settings.view' => ['View settings', 'settings'],
        'settings.manage' => ['Manage settings', 'settings'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Role definitions (tenant-scoped roles)
    |--------------------------------------------------------------------------
    */
    'roles' => [
        'super_admin' => [
            'name' => 'Super Admin',
            'is_system' => true,
            'platform_only' => true,
            'permissions' => '*',
        ],
        'company_owner' => [
            'name' => 'Company Owner',
            'is_system' => true,
            'permissions' => '*',
        ],
        'administrator' => [
            'name' => 'Administrator',
            'is_system' => true,
            'permissions' => '*',
        ],
        'branch_manager' => [
            'name' => 'Branch Manager',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'organization.companies.view',
                'organization.currencies.view',
                'organization.payment_methods.view',
                'organization.branches.view',
                'organization.branches.manage',
                'organization.stores.view',
                'organization.stores.manage',
                'organization.warehouses.view',
                'organization.warehouses.manage',
                'catalog.catalogs.view',
                'catalog.categories.view',
                'catalog.products.view',
                'catalog.barcodes.view',
                'sales.view',
                'sales.create',
                'sales.return',
                'sales.discount.apply',
                'promotions.view',
                'promotions.manage',
                'registers.view',
                'registers.manage',
                'registers.session.open',
                'registers.session.close',
                'registers.movement.record',
                'shifts.view',
                'shifts.manage',
                'shifts.open',
                'shifts.close',
                'shifts.movement.record',
                'inventory.view',
                'inventory.manage',
                'inventory.adjust',
                'inventory.transfer',
                'purchases.view',
                'purchases.manage',
                'purchases.receive',
                'customers.view',
                'customers.manage',
                'suppliers.view',
                'users.view',
                'reports.view',
                'settings.view',
            ],
        ],
        'store_manager' => [
            'name' => 'Store Manager',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'organization.stores.view',
                'organization.stores.manage',
                'catalog.products.view',
                'catalog.barcodes.view',
                'catalog.categories.view',
                'sales.view',
                'sales.create',
                'sales.return',
                'sales.discount.apply',
                'sales.void',
                'sales.return',
                'promotions.view',
                'registers.view',
                'registers.session.open',
                'registers.session.close',
                'registers.movement.record',
                'shifts.view',
                'shifts.manage',
                'shifts.open',
                'shifts.close',
                'shifts.movement.record',
                'inventory.view',
                'inventory.count.create',
                'inventory.count.enter',
                'inventory.count.review',
                'customers.view',
                'customers.manage',
                'users.view',
                'reports.view',
            ],
        ],
        'cashier' => [
            'name' => 'Cashier',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'catalog.products.view',
                'catalog.barcodes.view',
                'sales.view',
                'sales.create',
                'sales.return',
                'promotions.view',
                'registers.view',
                'registers.session.open',
                'registers.session.close',
                'registers.movement.record',
                'shifts.view',
                'shifts.open',
                'shifts.close',
                'shifts.movement.record',
                'customers.view',
                'customers.manage',
                'inventory.count.create',
                'inventory.count.enter',
            ],
        ],
        'inventory_manager' => [
            'name' => 'Inventory Manager',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'catalog.products.view',
                'catalog.products.manage',
                'catalog.barcodes.view',
                'catalog.barcodes.manage',
                'catalog.categories.view',
                'catalog.categories.manage',
                'inventory.view',
                'inventory.manage',
                'inventory.adjust',
                'inventory.transfer',
                'inventory.count.create',
                'inventory.count.enter',
                'inventory.count.review',
                'inventory.count.approve',
                'inventory.cycle.configure',
                'purchases.view',
                'purchases.manage',
                'purchases.receive',
                'suppliers.view',
                'suppliers.manage',
                'reports.view',
            ],
        ],
        'accountant' => [
            'name' => 'Accountant',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'sales.view',
                'purchases.view',
                'customers.view',
                'suppliers.view',
                'reports.view',
                'reports.export',
                'accounting.view',
                'accounting.manage',
            ],
        ],
        'sales_agent' => [
            'name' => 'Sales Agent',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'catalog.products.view',
                'sales.view',
                'sales.create',
                'sales.return',
                'sales.discount.apply',
                'promotions.view',
                'customers.view',
                'customers.manage',
            ],
        ],
        'auditor' => [
            'name' => 'Auditor',
            'is_system' => true,
            'permissions' => [
                'dashboard.view',
                'organization.companies.view',
                'organization.currencies.view',
                'organization.payment_methods.view',
                'organization.branches.view',
                'organization.stores.view',
                'catalog.products.view',
                'sales.view',
                'inventory.view',
                'purchases.view',
                'customers.view',
                'suppliers.view',
                'reports.view',
                'accounting.view',
                'audit.view',
                'users.view',
                'roles.view',
            ],
        ],
    ],

    'permission_cache_ttl' => 900,

];
